### ISSUE TITLE
support package-manifest with over 1k packages

### ISSUE THREAD

**Issue by scottford-lw** [lacework/go-sdk#237]
The `api/v1/external/vulnerabilities/scan` api has a limit of 1k per package manifest. It would be great if `generate-pkg-manifest` command could automatically break up the manifest into multiple files.

```
NOTE: Calls to this operation are rate limited to 10 calls per hour, per access key. If this rate limit is exceeded, an exception is thrown.
Also, note that this operation is limited to 1k of packages per payload. If you require a payload larger than 1k, you must make multiple requests.
For more information about creating an API access key and token to run this operation and using this operation with organization resources,
```

**Comment by afiune** [comment]
I think that it would be better if we make the `scan-pkg-manifest` command to support a single manifest file with over 1k packages. I feel that making the `generate-pkg-manifest` create multiple files will cause a bit more difficulties mainly because then the user would have to parse every file and submit multiple scans. Thoughts @scottford-lw ?

**Comment by scottford-lw** [comment]
@afiune I agree that would be a better user experience. It would be great to get some feedback from a customer on this as well. Can you ask in customer slack with the customer that inspired this one?
