### ISSUE TITLE
GCP List Projects Limited Output

### ISSUE THREAD

**Issue by MarkVLK** [lacework/go-sdk#496]
The `lacework compliance gcp list-projects <org_id>` command limits output to 5,000 projects which appears to be a limitation of the **/api/v1/external/compliance/gcp/ListProjectsForOrganization** endpoint. There is no flag/option to retrieve additional GCP projects.

**Comment by afiune** [comment]
Hi @MarkVLK - Thank you so much for your feedback! As you mentioned, this limitation is coming from
our APIs. We are currently working on migrating from API v1 to v2 and with this feedback, we will be able
to consider this enhancement so that, when the CLI uses the new v2 endpoint, we can have some sort of
pagination to retrieve more projects or, just return all the projects that your organization has all at once.

We are not yet sure what the actual implementation of this feature would look like, but we will definitely
keep you posted on any updates we have.

**JIRA:** https://lacework.atlassian.net/browse/RAIN-20593

**Comment by afiune** [comment]
Hey @MarkVLK - I'm swiping through old issues and found this one that is solved! 

Our new limit is 500,000 🙌🏽 

<img src="https://media4.giphy.com/media/l4pTgKSq2LDffuUIo/giphy.gif"/>
